### PR TITLE
docker_entrypoint.sh: change owner of PERSIST_DIRECTORY

### PR DESCRIPTION
**Pull request by rginev**
- make chroma user owner of $PERSIST_DIRECTORY, otherwise sqlite crashes

### CODE REVIEW

**Comment by tazarov** [comment]
Changed merge branch so I can fix the Chart version (need to move things into release branch at some point)

**Comment by rginev** [comment]
Thanks @tazarov !

**Comment by tazarov** [comment]
No, Thank you, @rginev! I also noticed that my actions don't have perms for ghcr push, so build fails, need to fix that one too

**Comment by tazarov** [comment]
@rginev new version is up. Thank you.

**Comment by rginev** [comment]
Thanks for the rapid update - it works beautifully!

**Pull request merged**
